In [ ]:
import numpy as np
import sys
sys.path.append("..")
from src.preprocess.binning import term_freq_bin


In [7]:
data_path = "C:/Users/rdbra/Documents/honoursProject/code_base/Hon_proj_RDB/GRN_work/data/sct_top5k.npz"
data = np.load(data_path)['data']
binned_data = term_freq_bin(data, num_bins=7)
print("Binned data:", binned_data) 
print(binned_data.max(), binned_data.min())

Percentage of non-zero values: 17.10%
Bin edges: [0.69314718 1.73760695 2.78206672 3.82652649 4.87098626 5.91544603
 6.9599058  8.00436556]
Binned data: [[0. 0. 0. ... 0. 0. 0.]
 [3. 3. 2. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 1. 0.]]
7.0 0.0


In [11]:
# Load the test binned data
test_binned_data_path = "C:/Users/rdbra/Documents/honoursProject/code_base/Hon_proj_RDB/GRN_work/data/sct_top5k_bin_test.npz"
test_binned_data = np.load(test_binned_data_path)['data']
print("Test Binned data:", test_binned_data)
print(test_binned_data.max(), test_binned_data.min())

Test Binned data: [[0. 0. 0. ... 0. 0. 0.]
 [3. 3. 2. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 1. 0.]]
7.0 0.0
